### ISSUE TITLE
Github Actions CI/CD для mospolyhelper

### ISSUE THREAD

**Issue by tonykolomeytsev** [mospolyhelper/mospolyhelper-android#95]
Хотел спросить, думали ли вы в сторону подключения CI/CD к своему проекту?

Просто можно подключить Github Actions и делать много разных штук при вливании пулл-реквестов и пушах в мастер, например:
1. Собирать билд приложения
2. Гонять тесты (хоть у вас их и не много пока)
3. Гонять линтер (например detekt)
4. Атоматически собирать APK или App Bundle 
5. Автоматически деплоить релизы в Google Play.
6. Получать уведомления о пулл-реквестах которые завалили какой-то из пунктов CI.

Ну и самое главное, можно разместить в readme красивый зеленый бейджик: ![](https://github.com/tonykolomeytsev/mpeiapp/workflows/Android%20build/badge.svg?branch=master)

**Comment by tipapro** [comment]
Мы не настолько продвинутые ещё)
Посмотрю, что это за вещь и как её использовать.
Ну а про тесты - у нас их вообще нет, а то что там есть - костыль для быстрого получения json напрямую на комп

**Comment by tonykolomeytsev** [comment]
Хорошо, самостоятельно нагуглите что такое Github Actions и как его юзать.
Если объяснять максимально коротко, то менять что-то в коде проекта не придется. В корневой директории проекта создается директория `.github/workflows` и там кладется YAML файлик с описанием пайплайна.

Самый простой пример, компилировать `master` после того как в него запушили:
```yaml
name: Android Debug Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew assembleDebug
```

Тут самые главные последние две строчки, остальное -- преамбула, так сказать.
Напоминаю, что могу сделать пулл-реквест с простейший пайплайном, чтоб вы дальше сами могли его допиливать
